name: ForceItemBattle
version: '${project.version}'
main: forceitembattle.Main
api-version: 1.18
commands:
  start:
    permission: battle.forceitem.command.start
  skip:
    permission: battle.forceitem.command.skip
  reset:
    permission: battle.forceitem.command.reset
