name: ForceItemBattle
version: '1.0'
main: forceitembattle.Main
api-version: 1.18
commands:
  start:
    permission: battle.forceitem.command.start
  settings:
    permission: battle.forceitem.command.settings
  skip:
    permission: battle.forceitem.command.skip
  reset:
    permission: battle.forceitem.command.reset
  invsee:
    permission: battle.forceitem.command.invsee
  top:
  bp:
